version: "3.2"
services:

  xenial:
    image: ubuntu:xenial
    volumes: 
      - type: bind
        source: .
        target: /opensc
    network_mode: "host"
    command:
      - /bin/bash
      - /opensc/OpenSC-build.sh
    tty: true

    #  artful:
    #    image: ubuntu:artful
    #    volumes: 
    #      - type: bind
    #        source: .
    #        target: /opensc
    #    network_mode: "host"
    #    command:
    #      - /bin/bash
    #      - /opensc/OpenSC-build.sh
    #    tty: true

  bionic:
    image: ubuntu:bionic
    volumes: 
      - type: bind
        source: .
        target: /opensc
    network_mode: "host"
    command:
      - /bin/bash
      - /opensc/OpenSC-build.sh
    tty: true

  cosmic:
    image: ubuntu:cosmic
    volumes: 
      - type: bind
        source: .
        target: /opensc
    network_mode: "host"
    command:
      - /bin/bash
      - /opensc/OpenSC-build.sh
    tty: true
    
  jessie:
    image: debian:jessie
    volumes: 
      - type: bind
        source: .
        target: /opensc
    network_mode: "host"
    command:
      - /bin/bash
      - /opensc/OpenSC-build.sh
    tty: true

  stretch:
    image: debian:stretch
    volumes: 
      - type: bind
        source: .
        target: /opensc
    network_mode: "host"
    command:
      - /bin/bash
      - /opensc/OpenSC-build.sh
    tty: true
